### ISSUE TITLE
errors with easyocr

### ISSUE THREAD

**Issue by ZiggyMar** [deepsidh9/Live-Valorant-Overlay#11]
![s](https://user-images.githubusercontent.com/80932373/160289742-f9d76952-6082-4107-a28e-c03bb4c281be.png)

(MAIN RESULTS {'blue': {'jett': {'agent': 'jett', 'name': 'Mama Ponneri', 'rankName': 'Gold 2', 'rr': 32, 'leaderboard': 0, 'level': '184', 'team': 'blue', 'alive': True, 'health': 100}}, 'red': {}}
127.0.0.1 - - [27/Mar/2022 11:51:56] "GET /start_match HTTP/1.1" 200 -
127.0.0.1 - - [27/Mar/2022 11:51:57] "GET /favicon.ico HTTP/1.1" 404 -
Traceback (most recent call last):
  File "C:\Users\marwa\Desktop\Live-Valorant-Overlay-main\app\components\get_live_frames.py", line 11, in <module>
    from live_details import LiveDetails
  File "C:\Users\marwa\Desktop\Live-Valorant-Overlay-main\app\components\live_details.py", line 10, in <module>
    from score import GetScore
  File "C:\Users\marwa\Desktop\Live-Valorant-Overlay-main\app\components\score.py", line 3, in <module>
    from easyocr import Reader
ModuleNotFoundError: No module named 'easyocr')

**Comment by deepsidh9** [comment]
Try installing easyocr properly if not already installed on your system.

**Comment by ZiggyMar** [comment]
127.0.0.1 - - [20/Apr/2022 11:40:37] "GET /start_match HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\Users\marwa\Desktop\Live-Valorant-Overlay-main\app\components\get_live_frames.py", line 11, in <module>
    from live_details import LiveDetails
  File "C:\Users\marwa\Desktop\Live-Valorant-Overlay-main\app\components\live_details.py", line 10, in <module>
    from score import GetScore
  File "C:\Users\marwa\Desktop\Live-Valorant-Overlay-main\app\components\score.py", line 3, in <module>
    from easyocr import Reader
  File "C:\Users\marwa\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "C:\Users\marwa\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\easyocr.py", line 3, in <module>
    from .detection import get_detector, get_textbox
  File "C:\Users\marwa\AppData\Local\Programs\Python\Python310\lib\site-packages\easyocr\detection.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
127.0.0.1 - - [20/Apr/2022 11:40:48] "GET /socket.io/?EIO=4&transport=polling&t=O17eXrw HTTP/1.1" 200 -
1 machine connected
127.0.0.1 - - [20/Apr/2022 11:40:48] "POST /socket.io/?EIO=4&transport=polling&t=O17eXsG&sid=pB4zGtAATOxKZLFFAAAC HTTP/1.1" 200 -
127.0.0.1 - - [20/Apr/2022 11:40:48] "GET /socket.io/?EIO=4&transport=polling&t=O17eXsH&sid=pB4zGtAATOxKZLFFAAAC HTTP/1.1" 200 -

**Comment by deepsidh9** [comment]
It says that it cannot find PIL, which is the Python library [Pillow](https://pypi.org/project/Pillow/), you need to install all the dependencies successfully first in order to run the app properly.

**Comment by n8ventures** [comment]
Use easyocr version 4.5.4.58

 `python -m pip install opencv-python==4.5.4.58`

the newest version of easyocr breaks the app.
